Tutor_SP23_BL2_NET104/Controllers/MathController.cs
using Buoi_2.Models;
using Microsoft.AspNetCore.Mvc;

namespace Buoi_2.Controllers
{
    public class MathController : Controller
    {
        public IActionResult Index()
        {
            // Menu các bài toán

            return View();
        }

        [Route("/{actionIndex:int}")]
        public IActionResult Action(int actionIndex)
        {
            switch (actionIndex)
            {
                case 1:
                    return RedirectToAction("Action1");
                case 2:
                    return RedirectToAction("Action2");
                case 3:
                    return RedirectToAction("Action3");
                default:
                    return RedirectToAction("Index");
            }
        }

        public IActionResult Action1(ModelForAction1 request)
        {
            int ketQua = 0;

            if (request != null)
            {
                switch (request.PhepTinh)
                {
                    case 1:
                        ketQua = request.So1 + request.So2;
                        break;
                    case 2:
                        ketQua = request.So1 - request.So2;
                        break;
                    case 3:
                        ketQua = request.So1 * request.So2;
                        break;
                    case 4:
                        ketQua = request.So1 / request.So2;
                        break;
                }
            }

            ViewBag.KetQua = ketQua;

            return View();
        }

        public IActionResult Action2(ModelForAction2 request)
        {
            float x = 0;

            if (request != null)
            {
                if (request.a == 0)
                {
                    x = -9999999999999;
                }
                else
                {
                    x = -(float)request.b / request.a;
                }
            }

            ViewBag.x = x;

            return View();
        }

        public IActionResult Action3(ModelForAction3 request)
        {
            float ketQua = 0;

            if (request != null)
            {
                ketQua = request.canh * request.canh;
            }

            ViewBag.KetQua = ketQua;

            return View();
        }
    }
}

Tutor_SP23_BL2_NET104/Views/Math/Action1.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

@using Buoi_2.Models;
BÀI 1

@model ModelForAction1

@{
    int ketQua = ViewBag.KetQua;
}

<div class="mx-3">
    <form class="row" action="~/Math/Action1">
        <div class="col-6">
            <div class="form-group my-2">
                <label for="Name">Số 1</label>
                @Html.TextBoxFor(m => m.So1, new { @class = "form-control" })
                @Html.ValidationMessageFor(Model => Model.So1, "", new { @class = "text-danger" })
            </div>
            <div class="form-group my-2">
                <label for="Name">Số 2</label>
                @Html.TextBoxFor(m => m.So2, new { @class = "form-control" })
                @Html.ValidationMessageFor(Model => Model.So2, "", new { @class = "text-danger" })
            </div>
            <div class="form-group my-2">
                <label for="Amount">Phép tính</label>
                @Html.TextBoxFor(m => m.PhepTinh, new { @class = "form-control" })
                @Html.ValidationMessageFor(Model => Model.PhepTinh, "", new { @class = "text-danger" })
            </div>

            <div class="row m-0 p-0">
                <button type="submit" class="col-5 btn btn-success rounded my-2">Tính toán</button>
                <div class="col-2"></div>
                <a href="/Math/Action1" class="col-5 btn btn-secondary rounded my-2">Làm mới</a>
            </div>
        </div>
    </form>

    <div class="form-group my-2">
        <label for="Price">Kết quả: @ketQua</label>
    </div>
</div>

Tutor_SP23_BL2_NET104/Views/Math/Action2.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

@using Buoi_2.Models;
BÀI 2

@model ModelForAction2

@{
    float ketQua = ViewBag.x;
}

<div class="mx-3">
    <form class="row" action="~/Math/Action2">
        <div class="col-6">
            <div class="form-group my-2">
                <label for="Name">Số a</label>
                @Html.TextBoxFor(m => m.a, new { @class = "form-control" })
                @Html.ValidationMessageFor(Model => Model.a, "", new { @class = "text-danger" })
            </div>
            <div class="form-group my-2">
                <label for="Name">Số b</label>
                @Html.TextBoxFor(m => m.b, new { @class = "form-control" })
                @Html.ValidationMessageFor(Model => Model.b, "", new { @class = "text-danger" })
            </div>
            <div class="row m-0 p-0">
                <button type="submit" class="col-5 btn btn-success rounded my-2">Tính toán</button>
                <div class="col-2"></div>
                <a href="/Math/Action2" class="col-5 btn btn-secondary rounded my-2">Làm mới</a>
            </div>
        </div>
    </form>

    <div class="form-group my-2">
        <label for="Price">Kết quả: @ketQua</label>
    </div>
</div>

Tutor_SP23_BL2_NET104/Views/Math/Action3.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

@using Buoi_2.Models;
BÀI 3

@model ModelForAction3

@{
    float ketQua = ViewBag.KetQua;
}

<div class="mx-3">
    <form class="row" action="~/Math/Action3">
        <div class="col-6">
            <div class="form-group my-2">
                <label for="Name">Cạnh</label>
                @Html.TextBoxFor(m => m.canh, new { @class = "form-control" })
                @Html.ValidationMessageFor(Model => Model.canh, "", new { @class = "text-danger" })
            </div>

            <div class="row m-0 p-0">
                <button type="submit" class="col-5 btn btn-success rounded my-2">Tính toán</button>
                <div class="col-2"></div>
                <a href="/Math/Action3" class="col-5 btn btn-secondary rounded my-2">Làm mới</a>
            </div>
        </div>
    </form>

    <div class="form-group my-2">
        <label for="Price">Kết quả: @ketQua</label>
    </div>
</div>

Tutor_SP23_BL2_NET104/Views/Math/Index.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<h1>MENU</h1>
<hr />

<table class="table">
    <thead>
        <tr>
            <th scope="col">STT</th>
            <th scope="col">Tên bài toán</th>
            <th scope="col">Chức năng</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Cộng trừ nhân chia 2 số nguyên</td>
            <td>@Html.ActionLink("Thực hiện", "Action", "Math", new{actionIndex = 1})</td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>Giải phương trình bậc 1</td>
            <td>@Html.ActionLink("Thực hiện", "Action", "Math", new{actionIndex = 2})</td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>Tính diện tích hình vuông</td>
            <td>@Html.ActionLink("Thực hiện", "Action", "Math", new{actionIndex = 3})</td>
        </tr>

    </tbody>
</table>